config/routes.rb
Rails.application.routes.draw do

  

  get 'operations/flow'
  get 'operations/install_script'
  get 'operations/index'

  root 'book_infos#index'

  resources :contact_contents

  resources :contactors

  resources :activation_codes

  resources :book_infos

  get 'upload/index'
  post 'upload/import'

end

app/models/contact_content.rb
class ContactContent < ActiveRecord::Base
  belongs_to :contactor
  validates_associated :contactor
end

app/controllers/contact_contents_controller.rb
class ContactContentsController < ApplicationController
  before_action :set_contact_content, only: [:show, :edit, :update, :destroy]

  # GET /contact_contents
  # GET /contact_contents.json
  def index
    @contact_contents = ContactContent.all
  end

  # GET /contact_contents/1
  # GET /contact_contents/1.json
  def show
  end

  # GET /contact_contents/new
  def new
    @contact_content = ContactContent.new

    if(params[:contactor_id] != nil)
      @contact_content.contactor = Contactor.find(params[:contactor_id])
    end
  end

  # GET /contact_contents/1/edit
  def edit
  end

  # POST /contact_contents
  # POST /contact_contents.json
  def create
    @contact_content = ContactContent.new(contact_content_params)

    respond_to do |format|
      if @contact_content.save
        format.html { redirect_to @contact_content.contactor, notice: 'Contact content was successfully created.' }
        format.json { render :show, status: :created, location: @contact_content }
      else
        format.html { render :new }
        format.json { render json: @contact_content.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /contact_contents/1
  # PATCH/PUT /contact_contents/1.json
  def update
    respond_to do |format|
      if @contact_content.update(contact_content_params)
        format.html { redirect_to @contact_content, notice: 'Contact content was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_content }
      else
        format.html { render :edit }
        format.json { render json: @contact_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_contents/1
  # DELETE /contact_contents/1.json
  def destroy
    @contact_content.destroy
    respond_to do |format|
      format.html { redirect_to contact_contents_url, notice: 'Contact content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_content
      @contact_content = ContactContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_content_params
      params.require(:contact_content).permit(:content_type, :content_desc, :solution, :contactor_id)
    end
end

app/helpers/contact_contents_helper.rb
module ContactContentsHelper
end

app/views/contact_contents/_form.html.haml
= form_for @contact_content, html: { class: "form form-horizontal contact_content" } do |f|
  .form-group
    = f.label :content_type, class: 'control-label'
    .controls
      = f.text_field :content_type, class: 'form-control', required: true
    = error_span(@contact_content[:content_type])
  .form-group
    = f.label :content_desc, class: 'control-label'
    .controls
      = f.text_field :content_desc, class: 'form-control', required: true
    = error_span(@contact_content[:content_desc])
  .form-group
    = f.label :solution, class: 'control-label'
    .controls
      = f.text_field :solution, class: 'form-control', required: true
    = error_span(@contact_content[:solution])
  .form-group
    = f.label :contactor_id, class: 'control-label'
    .controls
      = f.text_field :contactor_id, class: 'form-control', required: true
    = error_span(@contact_content[:contactor_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), contact_contents_path, :class => 'btn btn-default'

app/views/contact_contents/edit.html.haml
- model_class = ContactContent
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contact_contents/index.html.haml
- model_class = ContactContent
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:content_type)
      %th= model_class.human_attribute_name(:content_desc)
      %th= model_class.human_attribute_name(:solution)
      %th= model_class.human_attribute_name(:contactor_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @contact_contents.each do |contact_content|
      %tr
        %td= link_to contact_content.id, contact_content_path(contact_content)
        %td= contact_content.content_type
        %td= contact_content.content_desc
        %td= contact_content.solution
        %td= contact_content.contactor_id
        %td=l contact_content.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_content_path(contact_content), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), contact_content_path(contact_content), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_contact_content_path, :class => 'btn btn-primary'

app/views/contact_contents/new.html.haml
- model_class = ContactContent
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contact_contents/show.html.haml
- model_class = ContactContent
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:content_type) + ':'
  %br
  = @contact_content.content_type
%p
  %strong= model_class.human_attribute_name(:content_desc) + ':'
  %br
  = @contact_content.content_desc
%p
  %strong= model_class.human_attribute_name(:solution) + ':'
  %br
  = @contact_content.solution
%p
  %strong= model_class.human_attribute_name(:contactor_id) + ':'
  %br
  = @contact_content.contactor_id


= link_to t('.back', :default => t("helpers.links.back")), contact_contents_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_contact_content_path(@contact_content), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), contact_content_path(@contact_content), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'