config/routes.rb
Rails.application.routes.draw do

  

  get 'operations/flow'
  get 'operations/install_script'
  get 'operations/index'

  root 'book_infos#index'

  resources :contact_contents

  resources :contactors

  resources :activation_codes

  resources :book_infos

  get 'upload/index'
  post 'upload/import'

end

app/models/book_info.rb
class BookInfo < ActiveRecord::Base
  has_many :activation_codes

  validates :name, presence: true,uniqueness: true
end

app/controllers/book_infos_controller.rb
class BookInfosController < ApplicationController
  before_action :set_book_info, only: [:show, :edit, :update, :destroy]

  # GET /book_infos
  # GET /book_infos.json
  def index
    @book_infos = BookInfo.all
  end

  # GET /book_infos/1
  # GET /book_infos/1.json
  def show
  end

  # GET /book_infos/new
  def new
    @book_info = BookInfo.new
  end

  # GET /book_infos/1/edit
  def edit
  end

  # POST /book_infos
  # POST /book_infos.json
  def create
    @book_info = BookInfo.new(book_info_params)

    respond_to do |format|
      if @book_info.save
        format.html { redirect_to @book_info, notice: 'Book info was successfully created.' }
        format.json { render :show, status: :created, location: @book_info }
      else
        format.html { render :new }
        format.json { render json: @book_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_infos/1
  # PATCH/PUT /book_infos/1.json
  def update
    respond_to do |format|
      if @book_info.update(book_info_params)
        format.html { redirect_to @book_info, notice: 'Book info was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_info }
      else
        format.html { render :edit }
        format.json { render json: @book_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_infos/1
  # DELETE /book_infos/1.json
  def destroy
    @book_info.destroy
    respond_to do |format|
      format.html { redirect_to book_infos_url, notice: 'Book info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_info
      @book_info = BookInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_info_params
      params.require(:book_info).permit(:name)
    end
end

app/helpers/book_infos_helper.rb
module BookInfosHelper
end

app/views/book_infos/_form.html.haml
= form_for @book_info, html: { class: "form form-horizontal book_info" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@book_info[:name])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), book_infos_path, :class => 'btn btn-default'

app/views/book_infos/edit.html.haml
- model_class = BookInfo
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/book_infos/index.html.haml
- model_class = BookInfo
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= '书名'
      %th= '可用的激活码数量'
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @book_infos.each do |book_info|
      %tr
        %td= link_to book_info.id, book_info_path(book_info)
        %td= link_to t('.edit', :default => t(book_info.name)), edit_book_info_path(book_info)
        %td= book_info.activation_codes.length
        %td
          = link_to t('.edit', :default => t("获得激活码")), activation_codes_path(book_info), :class => 'btn btn-default btn-xs'

= link_to t('.new', :default => t("helpers.links.new")), new_book_info_path, :class => 'btn btn-primary'

app/views/book_infos/new.html.haml
- model_class = BookInfo
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/book_infos/show.html.haml
- model_class = BookInfo
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @book_info.name


= link_to t('.back', :default => t("helpers.links.back")), book_infos_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_book_info_path(@book_info), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), book_info_path(@book_info), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'