config/routes.rb
Rails.application.routes.draw do

  

  get 'operations/flow'
  get 'operations/install_script'
  get 'operations/index'

  root 'book_infos#index'

  resources :contact_contents

  resources :contactors

  resources :activation_codes

  resources :book_infos

  get 'upload/index'
  post 'upload/import'

end

app/models/contactor.rb
class Contactor < ActiveRecord::Base

  has_many :contact_contents
end

app/controllers/contactors_controller.rb
class ContactorsController < ApplicationController
  before_action :set_contactor, only: [:show, :edit, :update, :destroy]

  # GET /contactors
  # GET /contactors.json
  def index
    @contactors = Contactor.all
  end

  # GET /contactors/1
  # GET /contactors/1.json
  def show
  end

  # GET /contactors/new
  def new
    @contactor = Contactor.new
  end

  # GET /contactors/1/edit
  def edit
  end

  # POST /contactors
  # POST /contactors.json
  def create
    @contactor = Contactor.new(contactor_params)

    respond_to do |format|
      if @contactor.save
        format.html { redirect_to @contactor, notice: 'Contactor was successfully created.' }
        format.json { render :show, status: :created, location: @contactor }
      else
        format.html { render :new }
        format.json { render json: @contactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactors/1
  # PATCH/PUT /contactors/1.json
  def update
    respond_to do |format|
      if @contactor.update(contactor_params)
        format.html { redirect_to @contactor, notice: 'Contactor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contactor }
      else
        format.html { render :edit }
        format.json { render json: @contactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactors/1
  # DELETE /contactors/1.json
  def destroy
    @contactor.destroy
    respond_to do |format|
      format.html { redirect_to contactors_url, notice: 'Contactor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contactor
      @contactor = Contactor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contactor_params
      params.require(:contactor).permit(:name, :email, :phone)
    end
end

app/helpers/contactors_helper.rb
module ContactorsHelper
end

app/views/contactors/_form.html.haml
= form_for @contactor, html: { class: "form form-horizontal contactor" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@contactor[:name])
  .form-group
    = f.label :email, class: 'control-label'
    .controls
      = f.text_field :email, class: 'form-control', required: true
    = error_span(@contactor[:email])
  .form-group
    = f.label :phone, class: 'control-label'
    .controls
      = f.text_field :phone, class: 'form-control', required: true
    = error_span(@contactor[:phone])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), contactors_path, :class => 'btn btn-default'

app/views/contactors/edit.html.haml
- model_class = Contactor
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contactors/index.html.haml
- model_class = Contactor
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:phone)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @contactors.each do |contactor|
      %tr
        %td= link_to contactor.id, contactor_path(contactor)
        %td= contactor.name
        %td= contactor.email
        %td= contactor.phone
        %td=l contactor.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_contactor_path(contactor), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), contactor_path(contactor), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_contactor_path, :class => 'btn btn-primary'

app/views/contactors/new.html.haml
- model_class = Contactor
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/contactors/show.html.haml
- model_class = Contactor
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @contactor.name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @contactor.email
%p
  %strong= model_class.human_attribute_name(:phone) + ':'
  %br
  = @contactor.phone


= link_to t('.back', :default => t("helpers.links.back")), contactors_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_contactor_path(@contactor), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), contactor_path(@contactor), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'