config/routes.rb
Rails.application.routes.draw do

  

  get 'operations/flow'
  get 'operations/install_script'
  get 'operations/index'

  root 'book_infos#index'

  resources :contact_contents

  resources :contactors

  resources :activation_codes

  resources :book_infos

  get 'upload/index'
  post 'upload/import'

end

app/models/activation_code.rb
class ActivationCode < ActiveRecord::Base
  belongs_to :book_info
  # validates_associated :book_info
  validates :book_info , presence: true

  validates :serial_number, length: { is: 6 },uniqueness: true
  validates :code, presence: true,uniqueness: true
  validates :has_use, presence: true
	
end

app/controllers/activation_codes_controller.rb
class ActivationCodesController < ApplicationController
  before_action :set_activation_code, only: [:show, :edit, :update, :destroy]

  # GET /activation_codes
  # GET /activation_codes.json
  def index
    @activation_codes = ActivationCode.all
  end

  # GET /activation_codes/1
  # GET /activation_codes/1.json
  def show
  end

  # GET /activation_codes/new
  def new
    @activation_code = ActivationCode.new
  end

  # GET /activation_codes/1/edit
  def edit
  end

  # POST /activation_codes
  # POST /activation_codes.json
  def create
    @activation_code = ActivationCode.new(activation_code_params)

    respond_to do |format|
      if @activation_code.save
        format.html { redirect_to @activation_code, notice: 'Activation code was successfully created.' }
        format.json { render :show, status: :created, location: @activation_code }
      else
        format.html { render :new }
        format.json { render json: @activation_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activation_codes/1
  # PATCH/PUT /activation_codes/1.json
  def update
    respond_to do |format|
      if @activation_code.update(activation_code_params)
        format.html { redirect_to @activation_code, notice: 'Activation code was successfully updated.' }
        format.json { render :show, status: :ok, location: @activation_code }
      else
        format.html { render :edit }
        format.json { render json: @activation_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activation_codes/1
  # DELETE /activation_codes/1.json
  def destroy
    @activation_code.destroy
    respond_to do |format|
      format.html { redirect_to activation_codes_url, notice: 'Activation code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activation_code
      @activation_code = ActivationCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activation_code_params
      params.require(:activation_code).permit(:serial_number, :code, :has_use, :remark, :book_info_id)
    end
end

app/helpers/activation_codes_helper.rb
module ActivationCodesHelper
end

app/views/activation_codes/_form.html.haml
= form_for @activation_code, html: { class: "form form-horizontal activation_code" } do |f|
  .form-group
    = f.label :serial_number, class: 'control-label'
    .controls
      = f.text_field :serial_number, class: 'form-control', required: true
    = error_span(@activation_code[:serial_number])
  .form-group
    = f.label :code, class: 'control-label'
    .controls
      = f.text_field :code, class: 'form-control', required: true
    = error_span(@activation_code[:code])
  .form-group
    = f.label :has_use, class: 'control-label'
    .controls
      = f.text_field :has_use, class: 'form-control', required: true
    = error_span(@activation_code[:has_use])
  .form-group
    = f.label :remark, class: 'control-label'
    .controls
      = f.text_field :remark, class: 'form-control', required: true
    = error_span(@activation_code[:remark])
  .form-group
    = f.label :book_info_id, class: 'control-label'
    .controls
      = f.text_field :book_info_id, class: 'form-control', required: true
    = error_span(@activation_code[:book_info_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), activation_codes_path, :class => 'btn btn-default'

app/views/activation_codes/edit.html.haml
- model_class = ActivationCode
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/activation_codes/index.html.haml
- model_class = ActivationCode
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:serial_number)
      %th= model_class.human_attribute_name(:code)
      %th= model_class.human_attribute_name(:has_use)
      %th= model_class.human_attribute_name(:remark)
      %th= model_class.human_attribute_name(:book_info_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @activation_codes.each do |activation_code|
      %tr
        %td= link_to activation_code.id, activation_code_path(activation_code)
        %td= activation_code.serial_number
        %td= activation_code.code
        %td= activation_code.has_use
        %td= activation_code.remark
        %td= activation_code.book_info_id
        %td=l activation_code.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_activation_code_path(activation_code), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), activation_code_path(activation_code), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_activation_code_path, :class => 'btn btn-primary'

app/views/activation_codes/new.html.haml
- model_class = ActivationCode
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/activation_codes/show.html.haml
- model_class = ActivationCode
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:serial_number) + ':'
  %br
  = @activation_code.serial_number
%p
  %strong= model_class.human_attribute_name(:code) + ':'
  %br
  = @activation_code.code
%p
  %strong= model_class.human_attribute_name(:has_use) + ':'
  %br
  = @activation_code.has_use
%p
  %strong= model_class.human_attribute_name(:remark) + ':'
  %br
  = @activation_code.remark
%p
  %strong= model_class.human_attribute_name(:book_info_id) + ':'
  %br
  = @activation_code.book_info_id


= link_to t('.back', :default => t("helpers.links.back")), activation_codes_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_activation_code_path(@activation_code), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), activation_code_path(@activation_code), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'